# Generated by Django 4.2 on 2023-05-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pedido Realizado', 'Realizado'), ('Pedido em Andamento', 'Andamento'), ('Pedido Concluido', 'Concluido')], default='Pedido Realizado', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
